version: "2"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - ${MEDIA_DIR}:/data
      - /mnt/usb/apps/plex/library:/config
      - /mnt/usb/apps/plex/transcode:/transcode
    restart: unless-stopped
