---
name: Minecraft Server
maintainer: count-null
description: Run a minecraft server.
links:
  - label: Docker Image GitHub
    url: https://github.com/itzg/docker-aminecraft-server
open_link: false
needs_update: false
var_fields:
  - name: VERSION
    label: Version
    field: select
    options:
      - LATEST
      - SNAPSHOT
      - 1.16.3
      - 1.16.2
      - 1.16.1
      - "1.16"
    default: LATEST
  - field: select
    label: Server Type
    name: SERVER_TYPE
    options:
      - SPIGOT
      - FORGE
      - PAPER
      - TUINITY
      - MAGMA
      - MOHIST
      - CATSERVER
      - SPONGEVANILLA
      - FABRIC
    default: SPIGOT
