---
version: "2"
services:
  nextcloud:
    image: linuxserver/nextcloud
    container_name: nextcloud
    volumes:
      - /mnt/usb/apps/nextcloud/config:/config
      - /mnt/usb/apps/nextcloud/data:/data
    ports:
      - 8012:443
    restart: unless-stopped
